### ISSUE TITLE
v1.2.6 所有词典a href失效，所有词典Failed to add dictionary to context

### ISSUE THREAD

**Issue by ConcealedBlade** [Jimex/DintTango-Windows#5]
**Describe the bug**
v1.2.6 所有词典a href失效，所有词典Failed to add dictionary to context

**To Reproduce**
加入词典，进入阅读模式。点击跳转文字。

**Expected behavior**
[ERROR] ProcessRequestResource 
 Sequence contains no matching element    at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at DictTango.Core.Dictionary.Wrapper.MDictWrapper.DoMatchKeyword(String word, LookupMethods lookupMethod)
   at DictTango.Core.Dictionary.Server.Resource.DictServerResourceLoader.ProcessEntryContentResource(DictionaryResourceRequest request)
   at DictTango.Core.Dictionary.Server.Resource.DictServerResourceLoader.ProcessRequestResource(DictionaryResourceRequest request)

**Screenshots**
![image](https://github.com/Jimex/DintTango-Windows/assets/63355926/f45abfb2-6b61-4adc-88b1-5c2056492748)

**Application Info (please complete the following information):**
 - Version 1.2.6

**Operating System (please complete the following information):**
版本	Windows 11 专业版
版本	23H2
安装日期	‎2023/‎6/‎27
操作系统版本	22635.3066
体验	Windows Feature Experience Pack 1000.22685.1000.0

[App.7z|attachment](https://forum.freemdict.com/uploads/short-url/jXDAPc5fvPsdUXwg1Wct0DsPwVT.7z) (40.1 KB)

**Comment by ConcealedBlade** [comment]
删除所有应用数据后，卸载重装恢复正常。

**Comment by Jimex** [comment]
好，如果我这边碰到我再详细检查一下
